name: tommy_utils
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - nibabel
  - nilearn
  - seaborn=0.13.0
  - gensim
  - nltk
  - numpy=1.23
  - librosa
  - pandas=1.2.2
  - matplotlib
  - regex
  - moviepy
  - mesalib
  - libiconv
  - vtk==9.1.0=osmesa_py39h8ab48e2_107
  - joypy
  - pip
  - statsmodels
  - huggingface_hub
  - transformers>=4.51.0 #=4.35.0
  - scikit-learn
  - scipy
  - matplotlib
  - tqdm
  - praatio
  - einops
  - pip:
    - torchaudio
    - torchvision
    - av
    - torchlens
    - neuromaps
    - brainspace
    - mergedeep
    - himalaya
    - pydub
    # - tensorflow
    - natsort
    - sentencepiece
    - transformers_stream_generator
    - fasttext-wheel